[connections.snowflake]
account = "TSOEQSN-OJ08090"
password = "Snowflake.2025"
user = "RAYYAANS"
authenticator = "externalbrowser"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "FITNESS"
schema = "PUBLIC"
